#!/usr/bin/env php

<?php

exec('composer update --no-dev', $output, $status);

if ($status !== 0) {
	echo (implode("\n", $output));
	return -1;
}

$options = getopt('n', array('no-push'));

if (isset($options['no-push']) || isset($options['n'])) {
	return 0;
}

exec('git push', $output, $status);

if ($status !== 0) {
	echo (implode("\n", $output));
	return -1;
}

return 0;
